exercise_html_purifier:
    # full configuration reference: http://htmlpurifier.org/live/configdoc/plain.html
    html_profiles:
        custom:
            config:
                Core.Encoding: 'UTF-8'
                AutoFormat.AutoParagraph: true
