controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        fr: '/fr'
        ja: '/ja'
        zh-hans: '/zh-hans'
        pt-br: '/pt-br'
        hu: '/hu'
        es: '/es'
        de: '/de'
        ar: '/ar'
        ru: '/ru'
        it: '/it'
        sv: '/sv'
        ko: '/ko'
        el: '/el'
        bg: '/bg'
        cs: '/cs'
        da: '/da'
        et: '/et'
        fi: '/fi'
        ga: '/ga'
        lt: '/lt'
        lv: '/lt'
        mt: '/mt'
        nl: '/nl'
        pt: '/pt'
        ro: '/ro'
        sk: '/sk'
        sl: '/sl'
        en: '' # safety net: this is last to ensure a URL containing a locale is not considered as a parameter for an English route

kernel:
    resource: ../../src/Kernel.php
    type: annotation
