controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        af: '/af'
        ar: '/ar'
        bg: '/bg'
        cs: '/cs'
        da: '/da'
        de: '/de'
        el: '/el'
        es: '/es'
        et: '/et'
        fi: '/fi'
        fr: '/fr'
        ga: '/ga'
        hi: '/hi'
        hu: '/hu'
        it: '/it'
        ja: '/ja'
        ko: '/ko'
        lt: '/lt'
        lv: '/lv'
        mt: '/mt'
        nl: '/nl'
        pt-br: '/pt-br'
        pt: '/pt'
        ro: '/ro'
        ru: '/ru'
        sk: '/sk'
        sl: '/sl'
        sv: '/sv'
        zh-hans: '/zh-hans'
        zu: '/zu'
        en: '' # safety net: this is last to ensure a URL containing a locale is not considered as a parameter for an English route

kernel:
    resource: ../../src/Kernel.php
    type: annotation
