framework:
    assets:
        packages:
            website-2021:
                base_urls: 'https://www.w3.org/assets/website-2021/'
#                base_urls: '%env(ASSETS_WEBSITE_2021)%'
                base_path: ~
            logos:
                base_urls: 'https://www.w3.org/assets/logos/'
                base_path: ~
